# Generated by Django 4.2.7 on 2025-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='s3_key',
            field=models.CharField(blank=True, help_text='S3 object key for original file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videoresolution',
            name='s3_key',
            field=models.CharField(blank=True, help_text='S3 object key for processed file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/original/'),
        ),
        migrations.AlterField(
            model_name='videoresolution',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
