# Generated by Django 4.2.7 on 2025-10-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HLSVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('s3_key', models.CharField(blank=True, help_text='Original video S3 key', max_length=500)),
                ('master_playlist_s3_key', models.CharField(blank=True, help_text='Master playlist (master.m3u8) S3 key', max_length=500)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Original file size in bytes', null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HLS Video',
                'verbose_name_plural': 'HLS Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HLSVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(help_text='e.g., 480p, 720p, 1080p', max_length=10)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('bitrate', models.CharField(help_text='e.g., 1000k, 2500k', max_length=20)),
                ('playlist_s3_key', models.CharField(blank=True, help_text='Variant playlist S3 key', max_length=500)),
                ('segments_s3_prefix', models.CharField(blank=True, help_text='S3 prefix for .ts segments', max_length=500)),
                ('segment_duration', models.IntegerField(default=10, help_text='Segment duration in seconds')),
                ('segment_count', models.IntegerField(default=0, help_text='Number of segments')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='hls_videos.hlsvideo')),
            ],
            options={
                'verbose_name': 'HLS Variant',
                'verbose_name_plural': 'HLS Variants',
                'ordering': ['width'],
                'unique_together': {('video', 'resolution')},
            },
        ),
    ]
